### ISSUE TITLE
should define the roadmap for v0.2.0

### ISSUE THREAD

**Issue by hoatle** [teracyhq-incubator/kubernetes-stack-cookbook#23]
- [ ] code refactoring and improvements
- [ ] better unit test organization and reduce CI build time
- [ ] introduce "kubernetes" to install, remove kubernetes (1 node for now), installed kubernetes should work the same as minikube.

**Comment by hoatle** [comment]
considering adding this: https://www.telepresence.io/ (recommended by @minhchuduc)

**Comment by hoatle** [comment]
close for now, we're moving to https://github.com/teracyhq-incubator/teracy-dev-k8s instead.
